import type { NavigationSnapshot } from './types'

export const sampleSnapshot: NavigationSnapshot = {
  isConfigured: false,
  source: 'sample',
  totalCategories: 3,
  totalLinks: 7,
  groups: [
    {
      category: {
        id: 'sample-projects',
        name: '项目入口',
        description: '测试、生产与常用后台入口集中在一起。',
        sort: 10,
        isPublic: true,
      },
      links: [
        {
          id: 'sample-projects-test',
          name: 'NavSphere 测试环境',
          url: 'https://test.navsphere.dev',
          env: 'test',
          description: '联调、验证和回归测试入口。',
          icon: null,
          sort: 10,
          isPublic: true,
          categoryId: 'sample-projects',
        },
        {
          id: 'sample-projects-prod',
          name: 'NavSphere 生产环境',
          url: 'https://navsphere.dev',
          env: 'prod',
          description: '正式服务入口。',
          icon: null,
          sort: 20,
          isPublic: true,
          categoryId: 'sample-projects',
        },
      ],
    },
    {
      category: {
        id: 'sample-tools',
        name: '开发工具',
        description: 'CI、监控和仓库入口。',
        sort: 20,
        isPublic: true,
      },
      links: [
        {
          id: 'sample-tools-github',
          name: 'GitHub',
          url: 'https://github.com',
          env: 'prod',
          description: '代码仓库、PR 和 Issue。',
          icon: null,
          sort: 10,
          isPublic: true,
          categoryId: 'sample-tools',
        },
        {
          id: 'sample-tools-vercel',
          name: 'Vercel',
          url: 'https://vercel.com',
          env: 'prod',
          description: '前端部署与预览环境。',
          icon: null,
          sort: 20,
          isPublic: true,
          categoryId: 'sample-tools',
        },
      ],
    },
    {
      category: {
        id: 'sample-ai',
        name: 'AI 工具',
        description: '团队的对话式编程与研究入口。',
        sort: 30,
        isPublic: true,
      },
      links: [
        {
          id: 'sample-ai-chatgpt',
          name: 'ChatGPT',
          url: 'https://chatgpt.com',
          env: 'prod',
          description: '通用研究、写作与协作。',
          icon: null,
          sort: 10,
          isPublic: true,
          categoryId: 'sample-ai',
        },
        {
          id: 'sample-ai-claude',
          name: 'Claude',
          url: 'https://claude.ai',
          env: 'prod',
          description: '长上下文分析与代码协作。',
          icon: null,
          sort: 20,
          isPublic: true,
          categoryId: 'sample-ai',
        },
        {
          id: 'sample-ai-deepseek',
          name: 'DeepSeek',
          url: 'https://chat.deepseek.com',
          env: 'prod',
          description: '代码与推理场景补充入口。',
          icon: null,
          sort: 30,
          isPublic: true,
          categoryId: 'sample-ai',
        },
      ],
    },
  ],
}

